[package]
name = "glow_plus_sdl2"
version = "0.1.0"
edition = "2021"

[dependencies]
# Include egui_sdl2_platform
egui_sdl2_platform = { path = "../../", features = ["sdl2_use-pkgconfig"] }

gl = "0.14"
egui = "0.29"
egui_glow = "0.29"

pollster = "0.2"
anyhow = "1.0"
