[package]
name = "wgpu_plus_sdl2"
version = "0.1.0"
edition = "2021"

[dependencies]
# Include egui_sdl2_platform
egui_sdl2_platform = { path = "../../" }

wgpu = "23.0"
egui = "0.29"
egui_wgpu_backend = "0.32"
pollster = "0.2"
anyhow = "1.0"
